import { CanvasElement } from '@/hooks/useCanvas'

export interface Template {
  id: string
  name: string
  category: string
  isPremium: boolean
  width: number
  height: number
  background: {
    type: 'solid' | 'gradient'
    color?: string
    gradient?: { colors: [string, string]; angle: number }
  }
  elements: Omit<CanvasElement, 'id'>[]
}

export const TEMPLATES: Template[] = [
  // FREE TEMPLATES
  {
    id: 'bold-statement',
    name: 'Bold Statement',
    category: 'General',
    isPremium: false,
    width: 1280,
    height: 720,
    background: { type: 'solid', color: '#1a1a2e' },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 280,
        width: 900,
        height: 120,
        text: '10 TIPS FOR BETTER PRODUCTIVITY',
        fontSize: 72,
        fontFamily: 'Bebas Neue',
        fontStyle: '',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Heading',
        letterSpacing: 4,
        lineHeight: 1.1,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 420,
        width: 700,
        height: 60,
        text: 'Work smarter, not harder — boost your output today',
        fontSize: 28,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#adb5bd',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subheading',
        letterSpacing: 0,
        lineHeight: 1.4,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'shape',
        x: 640,
        y: 520,
        width: 200,
        height: 6,
        shapeType: 'rectangle',
        fill: '#5c7cfa',
        stroke: '',
        strokeWidth: 0,
        cornerRadius: 3,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Divider',
      },
    ],
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    category: 'General',
    isPremium: false,
    width: 1280,
    height: 720,
    background: { type: 'solid', color: '#faf9f6' },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 260,
        width: 800,
        height: 100,
        text: 'The Art of Simple Living',
        fontSize: 64,
        fontFamily: 'Playfair Display',
        fontStyle: '',
        textDecoration: '',
        fill: '#212529',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'shape',
        x: 640,
        y: 370,
        width: 80,
        height: 3,
        shapeType: 'rectangle',
        fill: '#212529',
        stroke: '',
        strokeWidth: 0,
        cornerRadius: 1,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Line',
      },
      {
        type: 'text',
        x: 640,
        y: 420,
        width: 600,
        height: 50,
        text: 'A guide to mindful productivity and intentional design',
        fontSize: 22,
        fontFamily: 'Raleway',
        fontStyle: '',
        textDecoration: '',
        fill: '#868e96',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 2,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'neon-glow',
    name: 'Neon Glow',
    category: 'General',
    isPremium: false,
    width: 1280,
    height: 720,
    background: { type: 'solid', color: '#0a0a0a' },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 300,
        width: 900,
        height: 140,
        text: 'CREATIVE\nDESIGN STUDIO',
        fontSize: 80,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#00f260',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Neon Text',
        letterSpacing: 6,
        lineHeight: 1.1,
        stroke: '#00f260',
        strokeWidth: 1,
        shadowEnabled: true,
        shadowColor: '#00f260',
        shadowBlur: 30,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 460,
        width: 500,
        height: 40,
        text: 'WHERE IDEAS COME TO LIFE',
        fontSize: 20,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#666666',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Tagline',
        letterSpacing: 8,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'gradient-wave',
    name: 'Gradient Wave',
    category: 'General',
    isPremium: false,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#667eea', '#764ba2'], angle: 135 } },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 280,
        width: 800,
        height: 100,
        text: 'The Future of AI',
        fontSize: 72,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Heading',
        letterSpacing: 0,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: true,
        shadowColor: 'rgba(0,0,0,0.3)',
        shadowBlur: 20,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        type: 'text',
        x: 640,
        y: 410,
        width: 600,
        height: 50,
        text: 'Exploring what comes next in technology',
        fontSize: 26,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: 'rgba(255,255,255,0.85)',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 1,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  // PREMIUM TEMPLATES
  {
    id: 'tech-review',
    name: 'Tech Review',
    category: 'Tech',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#0f0c29', '#302b63'], angle: 160 } },
    elements: [
      {
        type: 'shape',
        x: 200,
        y: 360,
        width: 340,
        height: 340,
        shapeType: 'rectangle',
        fill: 'rgba(255,255,255,0.05)',
        stroke: 'rgba(255,255,255,0.1)',
        strokeWidth: 1,
        cornerRadius: 20,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Image Placeholder',
      },
      {
        type: 'text',
        x: 820,
        y: 260,
        width: 500,
        height: 120,
        text: 'iPhone 16 Pro\nFull Review',
        fontSize: 56,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 820,
        y: 430,
        width: 500,
        height: 40,
        text: 'IS IT WORTH THE UPGRADE?',
        fontSize: 20,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#feca57',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Tagline',
        letterSpacing: 4,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'podcast-episode',
    name: 'Podcast Episode',
    category: 'Podcast',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#1a1a2e', '#16213e'], angle: 180 } },
    elements: [
      {
        type: 'shape',
        x: 200,
        y: 360,
        width: 280,
        height: 280,
        shapeType: 'circle',
        fill: 'rgba(92,124,250,0.15)',
        stroke: '#5c7cfa',
        strokeWidth: 2,
        cornerRadius: 0,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Mic Circle',
      },
      {
        type: 'text',
        x: 200,
        y: 360,
        width: 200,
        height: 40,
        text: 'EP 42',
        fontSize: 32,
        fontFamily: 'Bebas Neue',
        fontStyle: '',
        textDecoration: '',
        fill: '#5c7cfa',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Episode Number',
        letterSpacing: 4,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 800,
        y: 280,
        width: 550,
        height: 120,
        text: 'The Future of AI\nin Creative Work',
        fontSize: 50,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 800,
        y: 440,
        width: 400,
        height: 30,
        text: 'THE DEEP DIVE PODCAST',
        fontSize: 16,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#5c7cfa',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Show Name',
        letterSpacing: 6,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'tutorial-howto',
    name: 'Tutorial / How-To',
    category: 'Education',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#ff6b6b', '#feca57'], angle: 135 } },
    elements: [
      {
        type: 'shape',
        x: 640,
        y: 130,
        width: 250,
        height: 55,
        shapeType: 'rectangle',
        fill: 'rgba(0,0,0,0.25)',
        stroke: '',
        strokeWidth: 0,
        cornerRadius: 30,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Badge BG',
      },
      {
        type: 'text',
        x: 640,
        y: 130,
        width: 200,
        height: 40,
        text: 'STEP BY STEP',
        fontSize: 18,
        fontFamily: 'Poppins',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Badge',
        letterSpacing: 4,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 320,
        width: 900,
        height: 160,
        text: 'How to Build a\nWebsite from Scratch',
        fontSize: 68,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.15,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: true,
        shadowColor: 'rgba(0,0,0,0.2)',
        shadowBlur: 20,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        type: 'text',
        x: 640,
        y: 500,
        width: 600,
        height: 40,
        text: 'Complete beginner guide — no experience needed',
        fontSize: 22,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: 'rgba(255,255,255,0.9)',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 0,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'ecommerce-sale',
    name: 'E-commerce Sale',
    category: 'Business',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'solid', color: '#000000' },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 200,
        width: 600,
        height: 80,
        text: 'MEGA SALE',
        fontSize: 90,
        fontFamily: 'Bebas Neue',
        fontStyle: '',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Sale Title',
        letterSpacing: 8,
        lineHeight: 1,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 340,
        width: 400,
        height: 120,
        text: '70% OFF',
        fontSize: 110,
        fontFamily: 'Anton',
        fontStyle: '',
        textDecoration: '',
        fill: '#ff6b6b',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Discount',
        letterSpacing: 0,
        lineHeight: 1,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: true,
        shadowColor: '#ff6b6b',
        shadowBlur: 40,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 490,
        width: 500,
        height: 40,
        text: 'LIMITED TIME ONLY — SHOP NOW',
        fontSize: 22,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#adb5bd',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'CTA',
        letterSpacing: 4,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'Gaming',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#0f0c29', '#1a0a3e'], angle: 180 } },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 250,
        width: 800,
        height: 100,
        text: 'LEVEL UP',
        fontSize: 110,
        fontFamily: 'Bebas Neue',
        fontStyle: '',
        textDecoration: '',
        fill: '#ff6b6b',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 8,
        lineHeight: 1,
        stroke: '#ff6b6b',
        strokeWidth: 0,
        shadowEnabled: true,
        shadowColor: '#ff6b6b',
        shadowBlur: 30,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 380,
        width: 700,
        height: 60,
        text: 'Top 5 Games You Must Play in 2025',
        fontSize: 36,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 0,
        lineHeight: 1.3,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 480,
        width: 400,
        height: 30,
        text: 'EPIC GAMEPLAY REVIEWS',
        fontSize: 16,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#845ef7',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Channel',
        letterSpacing: 6,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'travel-lifestyle',
    name: 'Travel & Lifestyle',
    category: 'Lifestyle',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#13547a', '#80d0c7'], angle: 135 } },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 200,
        width: 400,
        height: 40,
        text: 'TRAVEL GUIDE 2025',
        fontSize: 18,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: 'rgba(255,255,255,0.7)',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Badge',
        letterSpacing: 6,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 340,
        width: 800,
        height: 120,
        text: 'Exploring Bali\non a Budget',
        fontSize: 64,
        fontFamily: 'Playfair Display',
        fontStyle: '',
        textDecoration: '',
        fill: '#ffffff',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.15,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: true,
        shadowColor: 'rgba(0,0,0,0.3)',
        shadowBlur: 20,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
      },
      {
        type: 'text',
        x: 640,
        y: 490,
        width: 500,
        height: 40,
        text: '7 Days, $500 — Everything You Need to Know',
        fontSize: 20,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: 'rgba(255,255,255,0.85)',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 0,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'business-corporate',
    name: 'Business / Corporate',
    category: 'Business',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#141e30', '#243b55'], angle: 160 } },
    elements: [
      {
        type: 'shape',
        x: 100,
        y: 360,
        width: 6,
        height: 300,
        shapeType: 'rectangle',
        fill: '#5c7cfa',
        stroke: '',
        strokeWidth: 0,
        cornerRadius: 3,
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Accent Line',
      },
      {
        type: 'text',
        x: 500,
        y: 280,
        width: 700,
        height: 100,
        text: 'Quarterly Business\nPerformance Report',
        fontSize: 52,
        fontFamily: 'Montserrat',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#ffffff',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.2,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 500,
        y: 440,
        width: 500,
        height: 30,
        text: 'Q4 2025 — GROWTH INSIGHTS',
        fontSize: 18,
        fontFamily: 'Poppins',
        fontStyle: '',
        textDecoration: '',
        fill: '#5c7cfa',
        align: 'left',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 4,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
  {
    id: 'food-recipe',
    name: 'Food & Recipe',
    category: 'Lifestyle',
    isPremium: true,
    width: 1280,
    height: 720,
    background: { type: 'gradient', gradient: { colors: ['#ffecd2', '#fcb69f'], angle: 135 } },
    elements: [
      {
        type: 'text',
        x: 640,
        y: 200,
        width: 300,
        height: 35,
        text: 'EASY RECIPE',
        fontSize: 18,
        fontFamily: 'Poppins',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#c0392b',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Tag',
        letterSpacing: 6,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 330,
        width: 800,
        height: 120,
        text: 'Homemade Pasta\nfrom Scratch',
        fontSize: 64,
        fontFamily: 'Playfair Display',
        fontStyle: 'bold',
        textDecoration: '',
        fill: '#2d3436',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Title',
        letterSpacing: 0,
        lineHeight: 1.15,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
      {
        type: 'text',
        x: 640,
        y: 490,
        width: 500,
        height: 40,
        text: 'Ready in 30 minutes — only 5 ingredients',
        fontSize: 22,
        fontFamily: 'Raleway',
        fontStyle: '',
        textDecoration: '',
        fill: '#636e72',
        align: 'center',
        opacity: 1,
        rotation: 0,
        visible: true,
        locked: false,
        name: 'Subtitle',
        letterSpacing: 0,
        lineHeight: 1.5,
        stroke: '',
        strokeWidth: 0,
        shadowEnabled: false,
        shadowColor: '#000000',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
      },
    ],
  },
]
